name: deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout 2016
        uses: actions/checkout@v3
        with:
          repository: 'thiagohersan-www/2016.FATA'
          ref: 'gh-pages'
          path: '2016'

      - name: Checkout 2017
        uses: actions/checkout@v3
        with:
          repository: 'thiagohersan-www/2017.FATA'
          ref: 'gh-pages'
          path: '2017'

      - name: Build
        run: |
          mkdir public
          cp -r CNAME index.html js ./public/
          mv ./2016 ./public/2016
          mv ./2017 ./public/2017

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
